### PR TITLE
[Fixes 961] Use default value also for literal_to_type

### LINKED ISSUE #961: Undefined local variable or method `default'
When running `rbs prototype rb` on class like this:

```ruby
class HelloWorld
  def self.world(str)
      str + 'world'
  end

  def hello
    self.class.world('hello')
  end
end
```

And exception is thrown
```
/usr/local/lib/ruby/gems/3.0.0/gems/rbs-2.3.0/lib/rbs/prototype/rb.rb:545:in `literal_to_type': undefined local variable or method `default'
```

### PR DESCRIPTION
**Pull request by lauratpa**
Fixes #961 

It seems that when this piece of code  https://github.com/ruby/rbs/pull/937/files#diff-207b29733058e35f6d05687cd78c9e8e4aec1d51e86f794ea1f5d5620d66027fR545 was moved to a new place, the `default` value variable got left behind.

This is a naive implementation to fix it.

### CODE REVIEW

**Review by ksss — COMMENTED** [review]
OMG, It's my mistake. 😱
How about use `untyped` instead of `default`?

File: lib/rbs/prototype/rb.rb [hunk 1]
```diff
@@ -542,7 +542,7 @@ def literal_to_type(node)
           when :freeze, :tap, :itself, :dup, :clone, :taint, :untaint, :extend
             literal_to_type(receiver)
           else
-            default
+            untyped
```
Comment (lauratpa) [inline lib/rbs/prototype/rb.rb:545]: @ksss Like this? :)

**Review by soutaro — APPROVED** [review]
Looks good. Will merge this tonight.
@ksss Let me know if it's not good for you.

File: lib/rbs/prototype/rb.rb (hunk 1 above)
Comment (ksss) [reply lib/rbs/prototype/rb.rb:545]: Thanks🌸

**Comment by ksss** [comment]
No problem. Thanks 🌸
