### PR TITLE
Fix error of prototype rb on hash spread syntax

### LINKED ISSUE #464: `rbs prototype rb` raise NoMethodError
Hi, I encounter `NoMethodError` raised at `lib/rbs/prototype/rb.rb:366` when I run the `rbs prototype rb` command in the following case.

Error message:

```
/usr/local/bundle/gems/rbs-0.16.0/lib/rbs/prototype/rb.rb:366:in `literal_to_type': undefined method `type' for nil:NilClass (NoMethodError)
```

Location:

https://github.com/ruby/rbs/blob/63688754d06b96f7edf21e6da102616e379bb3db/lib/rbs/prototype/rb.rb#L366

## Reproduction

Target Ruby file (`a.rb`):

```ruby
def a(foo:)
  { called: true, **({ foo: foo }.compact) }
end

pp a(foo: "Foo")
pp a(foo: nil)
```

Result of `ruby a.rb`:

```console
$ ruby a.rb
{:called=>true, :foo=>"Foo"}
{:called=>true}
```

Result of `rbs prototype rb a.rb`:

```console
$ rbs prototype rb a.rb
Traceback (most recent call last):
	27: from /usr/local/bundle/bin/rbs:23:in `<main>'
	26: from /usr/local/bundle/bin/rbs:23:in `load'
	25: from /usr/local/bundle/gems/rbs-0.16.0/exe/rbs:7:in `<top (required)>'
	24: from /usr/local/bundle/gems/rbs-0.16.0/lib/rbs/cli.rb:113:in `run'
	23: from /usr/local/bundle/gems/rbs-0.16.0/lib/rbs/cli.rb:550:in `run_prototype'
	22: from /usr/local/bundle/gems/rbs-0.16.0/lib/rbs/cli.rb:660:in `run_prototype_file'
	21: from /usr/local/bundle/gems/rbs-0.16.0/lib/rbs/cli.rb:660:in `each'
	20: from /usr/local/bundle/gems/rbs-0.16.0/lib/rbs/cli.rb:661:in `block in run_prototype_file'
	19: from /usr/local/bundle/gems/rbs-0.16.0/lib/rbs/prototype/rb.rb:55:in `parse'
	18: from /usr/local/bundle/gems/rbs-0.16.0/lib/rbs/prototype/rb.rb:251:in `process'
	17: from /usr/local/bundle/gems/rbs-0.16.0/lib/rbs/prototype/rb.rb:292:in `each_child'
	16: from /usr/local/bundle/gems/rbs-0.16.0/lib/rbs/prototype/rb.rb:284:in `each_node'
	15: from /usr/local/bundle/gems/rbs-0.16.0/lib/rbs/prototype/rb.rb:284:in `each'
	14: from /usr/local/bundle/gems/rbs-0.16.0/lib/rbs/prototype/rb.rb:286:in `block in each_node'
	13: from /usr/local/bundle/gems/rbs-0.16.0/lib/rbs/prototype/rb.rb:252:in `block in process'
	12: from /usr/local/bundle/gems/rbs-0.16.0/lib/rbs/prototype/rb.rb:251:in `process'
	11: from /usr/local/bundle/gems/rbs-0.16.0/lib/rbs/prototype/rb.rb:292:in `each_child'
	10: from /usr/local/bundle/gems/rbs-0.16.0/lib/rbs/prototype/rb.rb:284:in `each_node'
	 9: from /usr/local/bundle/gems/rbs-0.16.0/lib/rbs/prototype/rb.rb:284:in `each'
	 8: from /usr/local/bundle/gems/rbs-0.16.0/lib/rbs/prototype/rb.rb:286:in `block in each_node'
	 7: from /usr/local/bundle/gems/rbs-0.16.0/lib/rbs/prototype/rb.rb:252:in `block in process'
	 6: from /usr/local/bundle/gems/rbs-0.16.0/lib/rbs/prototype/rb.rb:120:in `process'
	 5: from /usr/local/bundle/gems/rbs-0.16.0/lib/rbs/prototype/rb.rb:300:in `function_type_from_body'
	 4: from /usr/local/bundle/gems/rbs-0.16.0/lib/rbs/prototype/rb.rb:361:in `function_return_type_from_body'
	 3: from /usr/local/bundle/gems/rbs-0.16.0/lib/rbs/prototype/rb.rb:421:in `literal_to_type'
	 2: from /usr/local/bundle/gems/rbs-0.16.0/lib/rbs/prototype/rb.rb:421:in `each_slice'
	 1: from /usr/local/bundle/gems/rbs-0.16.0/lib/rbs/prototype/rb.rb:423:in `block in literal_to_type'
/usr/local/bundle/gems/rbs-0.16.0/lib/rbs/prototype/rb.rb:366:in `literal_to_type': undefined method `type' for nil:NilClass (NoMethodError)
```

By the way, unless `.compact`, the command passes:

```diff
 def a(foo:)
-  { called: true, **({ foo: foo }.compact) }
+  { called: true, **({ foo: foo }) }
 end
```

```console
$ rbs prototype rb a.rb
class Object
  def a: (foo: untyped foo) -> { called: ::TrueClass, foo: untyped }
end

$ ruby a.rb
{:called=>true, :foo=>"Foo"}
{:called=>true, :foo=>nil}
```

## Environment

```console
$ ruby -v
ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x86_64-linux]

$ rbs -v
rbs 0.16.0
```

I would be pleased to help if you would need more information. Thank you.

### PR DESCRIPTION
**Pull request by pocke**
Fix #464

# Cause

Hash key will be a `nil` on hash spread syntax.
For example

```ruby
pp RubyVM::AbstractSyntaxTree.parse('{ called: true, **({ foo: foo }.compact) }')
```

```
(SCOPE@1:0-1:42
 tbl: []
 args: nil
 body:
   (HASH@1:0-1:42
      (LIST@1:2-1:39 (LIT@1:2-1:9 :called) (TRUE@1:10-1:14) nil # ← here
         (CALL@1:19-1:39
            (HASH@1:19-1:31
               (LIST@1:21-1:29 (LIT@1:21-1:25 :foo) (VCALL@1:26-1:29 :foo)
                  nil)) :compact nil) nil)))
```

# Solution

Determine key and value types as `untyped` if it a hash has `**`.

So, the type for the reported code will be the following.

```ruby
# ruby
def a(foo:)
  { called: true, **({ foo: foo }.compact) }
end
```

```bash
$ exe/rbs prototype rb test.rb
class Object
  def a: (foo: untyped foo) -> ::Hash[:called | untyped, ::TrueClass | untyped]
end
```

---

By the way, @ybiquitous says "unless .compact, the command passes:".
Because Ruby optimizes a hash spread for a hash literal.

```ruby
pp RubyVM::AbstractSyntaxTree.parse('{ called: true, **({ foo: foo }) }')
```

```
(SCOPE@1:0-1:34
 tbl: []
 args: nil
 body:
   (HASH@1:0-1:34
      (LIST@1:2-1:29 (LIT@1:2-1:9 :called) (TRUE@1:10-1:14)
         (LIT@1:21-1:25 :foo) (VCALL@1:26-1:29 :foo) nil)))
```

The AST does not have nil as a key.

### CODE REVIEW

File: lib/rbs/prototype/rb.rb [hunk 1]
```diff
@@ -411,16 +411,22 @@ def literal_to_type(node)
         when :HASH
           list = node.children[0]
           if list
-            children = list.children.compact
+            children = list.children
+            children.pop
```
Comment (pocke) [inline lib/rbs/prototype/rb.rb:415]: In RubyVM::AST, all list has trailing nil. It removed the nil by `compact` previously. But `compact` removes a nil for hash spread unexpectedly. So I changed `compact` to `pop`.

**Review by soutaro — APPROVED** [review]
🎉
